# Generated by Django 3.0.5 on 2020-07-23 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertest',
            name='first_name',
        ),
        migrations.AddField(
            model_name='usertest',
            name='collaborator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.Collaborator'),
        ),
        migrations.AddField(
            model_name='usertest',
            name='password',
            field=models.CharField(default='contraseña', max_length=30),
        ),
        migrations.AlterField(
            model_name='usertest',
            name='username',
            field=models.CharField(default='usuario', max_length=10),
        ),
    ]
